---
- hosts: localhost
  name: "Configure 'tuned' with AMD GPU control"
  roles:
    # role prepares/modifies 'tuned' with AMD GPU power/clock parameters
    # creates a new tuned profile made for each permutation of (base) 'tuned' profile + AMD powerplay profile
    - role: tuned_amdgpu
      # note: 'gpu_*' vars only apply with the 'custom' suffixed profiles created by this tooling
      # profiles based on the 'default' amdgpu power profile mode use default clocks
      gpu_clock_min: "750" # default 500
      gpu_clock_max: "2600" # default 2529
      gpumem_clock_static: "1050"
      # optional, applies offset (+/-) to GPU voltage by provided mV
      gpu_mv_offset: "-50"
      # '-50' undervolts GPU core voltage 50mV or 0.05V
      #
      # list of source tuned profiles available on Fedora (TODO: should dynamically discover)
      base_profiles:
        - balanced
        - desktop
        - latency-performance
        - network-latency
        - network-throughput
        - powersave
        - virtual-host
      #
      # mapping of typical Navi generation power profiles from:
      #   /sys/class/drm/card*/device/pp_power_profile_mode
      # ref: https://www.kernel.org/doc/html/v4.20/gpu/amdgpu.html#pp-power-profile-mode
      # 'pwr_cap_multi' is multiplied against board *limit* to determine profile wattage; 0.5 = 50%
      # values below reflect my 6900XT
      amdgpu_profiles:
        default:
          pwrmode: 0
          pwr_cap_multi: 0.789473684210526 # 255W - default
        3D:
          pwrmode: 1
          pwr_cap_multi: 0.789473684210526 # 255W - default
        VR:
          pwrmode: 4
          pwr_cap_multi: 0.789473684210526 # 255W - default
        compute:
          pwrmode: 5
          pwr_cap_multi: 0.789473684210526 # 255W - default
        custom:
          pwrmode: 6
          pwr_cap_multi: 0.869969040247678 # 281W - slight boost
      # both dictionaries are merged to create new 'tuned' profiles. eg:
      #   'balanced-amdgpu-default', 'balanced-amdgpu-3D', 'balanced-amdgpu-video'
