---
- hosts: localhost
  name: "Configure 'tuned' with AMD GPU control"
  roles:
    # role prepares/modifies 'tuned' with AMD GPU power/clock parameters
    # creates a new tuned profile made for each permutation of (base) 'tuned' profile + AMD powerplay profile
    - role: tuned_amdgpu
      # list of source tuned profiles available on Fedora (TODO: should dynamically discover)
      base_profiles:
        - balanced
        - desktop
        - latency-performance
        - network-latency
        - network-throughput
        - powersave
        - virtual-host
