---
- name: "Configure 'tuned' with AMD GPU control"
  hosts: localhost
  roles:
    # role prepares/modifies 'tuned' with AMD GPU power/clock parameters
    # creates a new tuned profile made for each permutation of (base) 'tuned' profile + AMD powerplay profile
    - role: tuned_amdgpu
