---
# tasks file for tuned_amdgpu
#
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

# note: power-profiles-daemon conflicts with tuned
# since F35 it must be removed so tuned may be installed
- name: Replace 'power-profiles-daemon' with 'tuned' on Fedora 35+
  ansible.builtin.package: # use with_items/pkg since 'dnf' module in Ansible doesn't support 'swap'
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - {name: 'power-profiles-daemon', state: 'absent'}
    - {name: 'tuned', state: 'present'}
  when:
    - ('power-profiles-daemon' in ansible_facts.packages) or ('tuned' not in ansible_facts.packages)
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version|int > 35
  register: fed_ppdtuned_swap
  become: true

- name: Install tuned
  ansible.builtin.package:
    name: tuned
    state: present
  when: (fed_ppdtuned_swap is not defined) or ('tuned' not in ansible_facts.packages)
  become: true

- name: Ensure dynamic tuning is disabled
  ansible.builtin.lineinfile:
    path: /etc/tuned/tuned-main.conf
    regexp: '^dynamic_tuning.*='
    line: 'dynamic_tuning = 0'
  notify: Restart tuned
  become: true

- name: Create custom profile directories
  ansible.builtin.file:
    state: directory
    path: /etc/tuned/{{ item.1 }}-amdgpu-{{ item.0 }}
    mode: "0755"
  with_nested:
    - "{{ amdgpu_profiles }}"
    - "{{ base_profiles }}"
  become: true

- name: Copy 'common' AMDGPU script for all profiles
  ansible.builtin.copy:
    src: profile-common.sh
    dest: "/etc/tuned/{{ item.1 }}-amdgpu-{{ item.0 }}/amdgpu-common.sh"
    mode: "0644"  # sourced, doesn't require executable bit
    owner: root
    group: root
  notify: Restart tuned
  with_nested:
    - "{{ amdgpu_profiles }}"
    - "{{ base_profiles }}"
  become: true

- name: Template custom AMDGPU profile scripts
  ansible.builtin.template:
    src: amdgpu-profile-{{ item.0 }}.sh.j2
    dest: /etc/tuned/{{ item.1 }}-amdgpu-{{ item.0 }}/amdgpu-clock.sh
    owner: root
    group: root
    mode: "0755"
  loop: "{{ amdgpu_profiles | product(base_profiles) | list }}"
  notify: Restart tuned
  become: true

- name: Template tuned.conf for custom profiles
  ansible.builtin.template:
    src: templates/tuned.conf.j2
    dest: /etc/tuned/{{ item.1 }}-amdgpu-{{ item.0 }}/tuned.conf
    owner: root
    group: root
    mode: "0644"
  with_nested:
    - "{{ amdgpu_profiles }}"
    - "{{ base_profiles }}"
  notify: Restart tuned
  become: true

- name: Ensure tuned is enabled
  ansible.builtin.service:
    name: tuned
    enabled: true
  become: true
