---
# defaults file for tuned_amdgpu
#
# adjust where profiles are rendered based on the 'tuned' release from package facts
tuned_amdgpu_profile_dir: "{{ '/etc/tuned' if ansible_facts['packages']['tuned'][0]['version'] is version('2.23.0', '<') else '/etc/tuned/profiles' }}"
