---
# note: 'gpu_*' vars only apply with the 'custom' suffixed profiles created by this tooling
# profiles based on the 'default' amdgpu power profile mode use default clocks
#
# the connected AMD GPU is automatically discovered - assumes one
# on swap to other AMD cards to avoid instability:
#   'rm -rfv /etc/tuned/*amdgpu*'
#
# default 500, for best performance: near maximum. applies with 'overclock' tuned profile
gpu_clock_min: "500"

# gpu_clock_max: "2675" # default 2524 for my card
gpu_clock_max: "2715"

gpumem_clock_static: "1075"

gpu_power_multi_def: 0.869969040247678  # 281W - real default
gpu_power_multi_oc: 1.0  # full board power capability
# other multipliers for 323W boards like mine:
#   300W: 0.928792569659443
#   310:  0.959752321981424
# sample worksheet in 'power_max multi tab calculator.ods'

gpu_mv_offset: "+60" # add 60mV or 0.06V
# gpu_mv_offset: "+150" # add 150mV or 0.15V
# gpu_mv_offset: "+133" # add 133mV or 0.133V
#      gpu_mv_offset: "+75" # add 75mV or 0.075V
#      gpu_mv_offset: "+125" # add 125mV or 0.125V
# '-50' undervolts GPU core voltage 50mV or 0.05V; untested - here be dragons/instability

# 'tuned' plugins - used to set the kernel cmdline via bootloader... and sysctl tunables
plugins:  # ref: https://github.com/redhat-performance/tuned/tree/master/tuned/plugins
  bootloader:  #  'cmdline' allows entries w/ a suffix, names should be unique across *all* profiles. values accept +/- operators
    cmdline_amdgpu_general: "delayacct nowatchdog kvm.ignore_msrs=1 kvm_amd.npt=1 amdgpu.ppfeaturemask=0xfff7ffff"
    cmdline_amdgpu_hugepages: "default_hugepagesz=1G hugepagesz=1G hugepages=16"
    cmdline_amdgpu_iommu: "amd_iommu=on iommu=pt"
    cmdline_amdgpu_devs: "nvme_core.default_ps_max_latency_us=0 pci=realloc=off"
  sysctl:  # quote ints/cast to string to avoid surprises
    kernel.dmesg_restrict: '0'  # allow regular users to see the kernel ring buffer
    # net.core.default_qdisc: fq  # congestion control
    # net.ipv4.tcp_congestion_control: bbr2  # cong. control part 2
    # net.core.rmem_max: '33554432'
    # net.core.wmem_max: '33554432'
    dev.raid.speed_limit_min: '65000000'
    dev.raid.speed_limit_max: '99999999'
    vm.compaction_proactiveness: '30'  # improve THP allocation latency, compact in background
    vm.page_lock_unfairness: '1'  # make page lock theft slightly more fair
    vm.max_map_count: '1048576'  # allow some games to run (eg: DayZ)
